os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

dist: trusty
sudo: false

osx_image: xcode8

addons:
  apt:
    packages:
      - valgrind
      - libc6-dev-i386
      - gcc-multilib

env:
  matrix:
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
      ARCH=x86
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
      ARCH=x64

matrix:
  exclude:
    - compiler: gcc
      os: osx

before_script:
  - if [ ! -d deps/deps_build/lib ]; then scripts/build_deps.sh; fi

script:
  - mkdir build &&
    cd build &&
    cmake $CMAKE_OPTIONS -DNEKIT_ARCH:STRING=$ARCH .. &&
    cmake --build . 
  - ctest --output-on-failure
