os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

dist: trusty
sudo: false

osx_image: xcode8

addons:
  apt:
    packages:
      - valgrind

env:
  matrix:
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"

before_install:

script:
  - mkdir build &&
    cd build &&
    cmake .. $CMAKE_OPTIONS &&
    cmake --build . 
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then ctest --output-on-failure; fi
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then ctest -T memcheck --output-on-failure; fi
