os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

dist: trusty
sudo: false

osx_image: xcode8.2

addons:
  apt:
    packages:
      - valgrind
      - libc6-dev-i386
      - gcc-multilib
      # - linux-libc-dev:i386

env:
  global:
    - SHARED_CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=COVERAGE -DNELOG"
  matrix:
    - ARCH="x32"
      CMAKE_OPTIONS=""
    - ARCH="x64"
      CMAKE_OPTIONS=""


matrix:
  exclude:
    - compiler: gcc
      os: osx
    - compiler: clang
      env: ARCH="x32"
      os: linux

before_script:
  - if [ ! -d deps/deps_build/lib ]; then scripts/build_deps.sh; fi

script:
  - mkdir build &&
    cd build &&
    cmake $SHARED_CMAKE_OPTIONS $CMAKE_OPTIONS -DNEKIT_ARCH=$ARCH .. &&
    cmake --build . 
  - ctest --output-on-failure

after_success:
  - bash <(curl -s https://codecov.io/bash)
