os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

env:
  matrix:
    - CMAKE_OPTIONS=""

before_install:

script:
  - mkdir build &&
    cd build &&
    cmake .. $CMAKE_OPTIONS &&
    cmake --build .
