os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

dist: trusty
sudo: false

osx_image:
  matrix:
    - xcode8.2
    - xcode8.1
    - xcode8
    - xcode7.3

env:
  matrix:
    - CMAKE_OPTIONS=""

before_install:

script:
  - mkdir build &&
    cd build &&
    cmake .. $CMAKE_OPTIONS &&
    cmake --build .
