os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

dist: trusty
sudo: false

osx_image: xcode8

addons:
  apt:
    packages:
      - valgrind

env:
  matrix:
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"

cache:
  directories:
    - deps/deps_build

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      if [ "$CC" == "gcc" ]; then
        export CC=$(ls -t /usr/local/bin/gcc-?.?);
      fi
    fi

before_script:
  - if [ ! -d deps/deps_build/lib ]; then scripts/build_deps.sh; fi

script:
  - mkdir build &&
    cd build &&
    cmake .. $CMAKE_OPTIONS &&
    cmake --build . 
  - ctest --output-on-failure
