os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

dist: trusty
sudo: false

osx_image: xcode8

env:
  matrix:
    - CMAKE_OPTIONS=""

before_install:

script:
  - mkdir build &&
    cd build &&
    cmake .. $CMAKE_OPTIONS &&
    cmake --build . &&
    ctest --output-on-failure .
