os:
  - linux
  - osx

language: c
compiler:
- clang
- gcc

dist: trusty
sudo: false

osx_image: xcode8

addons:
  apt:
    packages:
      - valgrind

env:
  matrix:
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"

cache:
  directories:
    - deps/deps_build

before_script:
  - if [ ! -d deps/deps_build ]; then script/build_deps.sh; fi

script:
  - mkdir build &&
    cd build &&
    cmake .. $CMAKE_OPTIONS &&
    cmake --build . 
  - ctest --output-on-failure
